/* cand_neon_sb_bulk.c — Apple M4 NEON FastLanes scan, SUB-BYTE BULK PER-WORD UNPACK
 * with BYTE-PACKED COMPARE.
 *
 * Contract:
 *   uint64_t fl_scan_candidate(const uint32_t *planar, size_t n, unsigned b, uint32_t target)
 *
 * Strategy (the amortization wins, stacked):
 *  (1) BULK PER-WORD UNPACK: for width b each lane's 32 values occupy exactly b
 *      consecutive 32-bit word-rows (base[w*32 + l]). Load each word-row ONCE (8
 *      uint32x4 across the 32 lanes); every output position is decoded from those
 *      already-loaded words with a compile-time immediate shift + mask. Only the few
 *      boundary-straddling positions touch the next word (also already loaded).
 *  (2) BYTE-PACKED COMPARE: sub-byte values are <=127, so after field isolation each
 *      sits in the low byte of a u32 lane. Narrow-pack 4 decoded u32x4 (16 values)
 *      into one u8x16 and do a SINGLE vceqq_u8 for all 16 — 16 values per compare
 *      instead of 4. Matches accumulate in u16 (max 32/block/lane fits u16).
 *
 * Net: loads ~b word-rows/block; compares ~2b/block; ops/value ~0.5. Per-b switch
 * keeps all shift counts compile-time immediates. A general scalar fallback keeps a
 * full sweep (any width) correct if run without BBS_WIDTHS.
 * Generated by gen_sb_bulk.py.
 */
#include <stdint.h>
#include <stddef.h>
#include <arm_neon.h>

#define FL_LANES 32
#define FL_BLOCK 1024

static inline uint32_t mask_b(unsigned b) { return b >= 32 ? 0xFFFFFFFFu : ((1u << b) - 1u); }

/* pack 4 u32x4 (decoded value in low byte of each lane) -> one u8x16 (16 values)
 * via a narrow chain (vcombine is a free register alias; 6 vmovn do the work). */
static inline uint8x16_t pack4(uint32x4_t a, uint32x4_t b, uint32x4_t c, uint32x4_t d) {
    uint16x8_t ab = vcombine_u16(vmovn_u32(a), vmovn_u32(b));
    uint16x8_t cd = vcombine_u16(vmovn_u32(c), vmovn_u32(d));
    return vcombine_u8(vmovn_u16(ab), vmovn_u16(cd));
}

/* General scalar fallback: identical semantics to the seed, any width. */
static uint64_t scan_general(const uint32_t *planar, size_t blocks, unsigned b, uint32_t target) {
    uint32_t m = mask_b(b);
    target &= m;
    uint64_t count = 0;
    for (size_t blk = 0; blk < blocks; blk++) {
        const uint32_t *base = planar + blk * (size_t)b * FL_LANES;
        uint32_t partial[FL_LANES] = {0};
        for (unsigned p = 0; p < 32; p++) {
            unsigned bit = p * b, wp = bit >> 5, off = bit & 31;
            const uint32_t *pw = base + wp * FL_LANES;
            if (off == 0) {
                for (unsigned l = 0; l < FL_LANES; l++)
                    partial[l] += ((pw[l] & m) == target);
            } else {
                const uint32_t *pw1 = base + (wp + 1) * FL_LANES;
                for (unsigned l = 0; l < FL_LANES; l++) {
                    uint32_t v = ((pw[l] >> off) | (pw1[l] << (32 - off))) & m;
                    partial[l] += (v == target);
                }
            }
        }
        for (unsigned l = 0; l < FL_LANES; l++) count += partial[l];
    }
    return count;
}


static uint64_t scan_b1(const uint32_t *planar, size_t blocks, uint32_t target) {
    const uint8x16_t Mb = vdupq_n_u8((uint8_t)mask_b(1));
    const uint8x16_t T = vdupq_n_u8((uint8_t)(target & mask_b(1)));
    uint64_t count = 0;
    for (size_t blk = 0; blk < blocks; blk++) {
        const uint32_t *base = planar + blk * (size_t)1 * FL_LANES;
        __builtin_prefetch(base + (size_t)1 * FL_LANES, 0, 0);
        uint8x16_t acc0 = vdupq_n_u8(0), acc1 = vdupq_n_u8(0);
        for (int q = 0; q < 8; q++) {
            uint32x4_t w0 = vld1q_u32(base + 0*FL_LANES + q*4);
            uint32x4_t v[32];
            v[0] = w0;
            v[1] = vshrq_n_u32(w0, 1);
            v[2] = vshrq_n_u32(w0, 2);
            v[3] = vshrq_n_u32(w0, 3);
            v[4] = vshrq_n_u32(w0, 4);
            v[5] = vshrq_n_u32(w0, 5);
            v[6] = vshrq_n_u32(w0, 6);
            v[7] = vshrq_n_u32(w0, 7);
            v[8] = vshrq_n_u32(w0, 8);
            v[9] = vshrq_n_u32(w0, 9);
            v[10] = vshrq_n_u32(w0, 10);
            v[11] = vshrq_n_u32(w0, 11);
            v[12] = vshrq_n_u32(w0, 12);
            v[13] = vshrq_n_u32(w0, 13);
            v[14] = vshrq_n_u32(w0, 14);
            v[15] = vshrq_n_u32(w0, 15);
            v[16] = vshrq_n_u32(w0, 16);
            v[17] = vshrq_n_u32(w0, 17);
            v[18] = vshrq_n_u32(w0, 18);
            v[19] = vshrq_n_u32(w0, 19);
            v[20] = vshrq_n_u32(w0, 20);
            v[21] = vshrq_n_u32(w0, 21);
            v[22] = vshrq_n_u32(w0, 22);
            v[23] = vshrq_n_u32(w0, 23);
            v[24] = vshrq_n_u32(w0, 24);
            v[25] = vshrq_n_u32(w0, 25);
            v[26] = vshrq_n_u32(w0, 26);
            v[27] = vshrq_n_u32(w0, 27);
            v[28] = vshrq_n_u32(w0, 28);
            v[29] = vshrq_n_u32(w0, 29);
            v[30] = vshrq_n_u32(w0, 30);
            v[31] = vshrq_n_u32(w0, 31);
            uint8x16_t pk0 = vandq_u8(pack4(v[0], v[1], v[2], v[3]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk0, T));
            uint8x16_t pk1 = vandq_u8(pack4(v[4], v[5], v[6], v[7]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk1, T));
            uint8x16_t pk2 = vandq_u8(pack4(v[8], v[9], v[10], v[11]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk2, T));
            uint8x16_t pk3 = vandq_u8(pack4(v[12], v[13], v[14], v[15]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk3, T));
            uint8x16_t pk4 = vandq_u8(pack4(v[16], v[17], v[18], v[19]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk4, T));
            uint8x16_t pk5 = vandq_u8(pack4(v[20], v[21], v[22], v[23]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk5, T));
            uint8x16_t pk6 = vandq_u8(pack4(v[24], v[25], v[26], v[27]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk6, T));
            uint8x16_t pk7 = vandq_u8(pack4(v[28], v[29], v[30], v[31]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk7, T));
        }
        count += (uint64_t)vaddlvq_u8(acc0) + (uint64_t)vaddlvq_u8(acc1);
    }
    return count;
}

static uint64_t scan_b2(const uint32_t *planar, size_t blocks, uint32_t target) {
    const uint8x16_t Mb = vdupq_n_u8((uint8_t)mask_b(2));
    const uint8x16_t T = vdupq_n_u8((uint8_t)(target & mask_b(2)));
    uint64_t count = 0;
    for (size_t blk = 0; blk < blocks; blk++) {
        const uint32_t *base = planar + blk * (size_t)2 * FL_LANES;
        __builtin_prefetch(base + (size_t)2 * FL_LANES, 0, 0);
        uint8x16_t acc0 = vdupq_n_u8(0), acc1 = vdupq_n_u8(0);
        for (int q = 0; q < 8; q++) {
            uint32x4_t w0 = vld1q_u32(base + 0*FL_LANES + q*4);
            uint32x4_t w1 = vld1q_u32(base + 1*FL_LANES + q*4);
            uint32x4_t v[32];
            v[0] = w0;
            v[1] = vshrq_n_u32(w0, 2);
            v[2] = vshrq_n_u32(w0, 4);
            v[3] = vshrq_n_u32(w0, 6);
            v[4] = vshrq_n_u32(w0, 8);
            v[5] = vshrq_n_u32(w0, 10);
            v[6] = vshrq_n_u32(w0, 12);
            v[7] = vshrq_n_u32(w0, 14);
            v[8] = vshrq_n_u32(w0, 16);
            v[9] = vshrq_n_u32(w0, 18);
            v[10] = vshrq_n_u32(w0, 20);
            v[11] = vshrq_n_u32(w0, 22);
            v[12] = vshrq_n_u32(w0, 24);
            v[13] = vshrq_n_u32(w0, 26);
            v[14] = vshrq_n_u32(w0, 28);
            v[15] = vshrq_n_u32(w0, 30);
            v[16] = w1;
            v[17] = vshrq_n_u32(w1, 2);
            v[18] = vshrq_n_u32(w1, 4);
            v[19] = vshrq_n_u32(w1, 6);
            v[20] = vshrq_n_u32(w1, 8);
            v[21] = vshrq_n_u32(w1, 10);
            v[22] = vshrq_n_u32(w1, 12);
            v[23] = vshrq_n_u32(w1, 14);
            v[24] = vshrq_n_u32(w1, 16);
            v[25] = vshrq_n_u32(w1, 18);
            v[26] = vshrq_n_u32(w1, 20);
            v[27] = vshrq_n_u32(w1, 22);
            v[28] = vshrq_n_u32(w1, 24);
            v[29] = vshrq_n_u32(w1, 26);
            v[30] = vshrq_n_u32(w1, 28);
            v[31] = vshrq_n_u32(w1, 30);
            uint8x16_t pk0 = vandq_u8(pack4(v[0], v[1], v[2], v[3]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk0, T));
            uint8x16_t pk1 = vandq_u8(pack4(v[4], v[5], v[6], v[7]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk1, T));
            uint8x16_t pk2 = vandq_u8(pack4(v[8], v[9], v[10], v[11]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk2, T));
            uint8x16_t pk3 = vandq_u8(pack4(v[12], v[13], v[14], v[15]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk3, T));
            uint8x16_t pk4 = vandq_u8(pack4(v[16], v[17], v[18], v[19]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk4, T));
            uint8x16_t pk5 = vandq_u8(pack4(v[20], v[21], v[22], v[23]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk5, T));
            uint8x16_t pk6 = vandq_u8(pack4(v[24], v[25], v[26], v[27]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk6, T));
            uint8x16_t pk7 = vandq_u8(pack4(v[28], v[29], v[30], v[31]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk7, T));
        }
        count += (uint64_t)vaddlvq_u8(acc0) + (uint64_t)vaddlvq_u8(acc1);
    }
    return count;
}

static uint64_t scan_b3(const uint32_t *planar, size_t blocks, uint32_t target) {
    const uint8x16_t Mb = vdupq_n_u8((uint8_t)mask_b(3));
    const uint8x16_t T = vdupq_n_u8((uint8_t)(target & mask_b(3)));
    uint64_t count = 0;
    for (size_t blk = 0; blk < blocks; blk++) {
        const uint32_t *base = planar + blk * (size_t)3 * FL_LANES;
        __builtin_prefetch(base + (size_t)3 * FL_LANES, 0, 0);
        uint8x16_t acc0 = vdupq_n_u8(0), acc1 = vdupq_n_u8(0);
        for (int q = 0; q < 8; q++) {
            uint32x4_t w0 = vld1q_u32(base + 0*FL_LANES + q*4);
            uint32x4_t w1 = vld1q_u32(base + 1*FL_LANES + q*4);
            uint32x4_t w2 = vld1q_u32(base + 2*FL_LANES + q*4);
            uint32x4_t v[32];
            v[0] = w0;
            v[1] = vshrq_n_u32(w0, 3);
            v[2] = vshrq_n_u32(w0, 6);
            v[3] = vshrq_n_u32(w0, 9);
            v[4] = vshrq_n_u32(w0, 12);
            v[5] = vshrq_n_u32(w0, 15);
            v[6] = vshrq_n_u32(w0, 18);
            v[7] = vshrq_n_u32(w0, 21);
            v[8] = vshrq_n_u32(w0, 24);
            v[9] = vshrq_n_u32(w0, 27);
            v[10] = vorrq_u32(vshrq_n_u32(w0, 30), vshlq_n_u32(w1, 2));
            v[11] = vshrq_n_u32(w1, 1);
            v[12] = vshrq_n_u32(w1, 4);
            v[13] = vshrq_n_u32(w1, 7);
            v[14] = vshrq_n_u32(w1, 10);
            v[15] = vshrq_n_u32(w1, 13);
            v[16] = vshrq_n_u32(w1, 16);
            v[17] = vshrq_n_u32(w1, 19);
            v[18] = vshrq_n_u32(w1, 22);
            v[19] = vshrq_n_u32(w1, 25);
            v[20] = vshrq_n_u32(w1, 28);
            v[21] = vorrq_u32(vshrq_n_u32(w1, 31), vshlq_n_u32(w2, 1));
            v[22] = vshrq_n_u32(w2, 2);
            v[23] = vshrq_n_u32(w2, 5);
            v[24] = vshrq_n_u32(w2, 8);
            v[25] = vshrq_n_u32(w2, 11);
            v[26] = vshrq_n_u32(w2, 14);
            v[27] = vshrq_n_u32(w2, 17);
            v[28] = vshrq_n_u32(w2, 20);
            v[29] = vshrq_n_u32(w2, 23);
            v[30] = vshrq_n_u32(w2, 26);
            v[31] = vshrq_n_u32(w2, 29);
            uint8x16_t pk0 = vandq_u8(pack4(v[0], v[1], v[2], v[3]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk0, T));
            uint8x16_t pk1 = vandq_u8(pack4(v[4], v[5], v[6], v[7]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk1, T));
            uint8x16_t pk2 = vandq_u8(pack4(v[8], v[9], v[10], v[11]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk2, T));
            uint8x16_t pk3 = vandq_u8(pack4(v[12], v[13], v[14], v[15]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk3, T));
            uint8x16_t pk4 = vandq_u8(pack4(v[16], v[17], v[18], v[19]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk4, T));
            uint8x16_t pk5 = vandq_u8(pack4(v[20], v[21], v[22], v[23]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk5, T));
            uint8x16_t pk6 = vandq_u8(pack4(v[24], v[25], v[26], v[27]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk6, T));
            uint8x16_t pk7 = vandq_u8(pack4(v[28], v[29], v[30], v[31]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk7, T));
        }
        count += (uint64_t)vaddlvq_u8(acc0) + (uint64_t)vaddlvq_u8(acc1);
    }
    return count;
}

static uint64_t scan_b4(const uint32_t *planar, size_t blocks, uint32_t target) {
    const uint8x16_t Mb = vdupq_n_u8((uint8_t)mask_b(4));
    const uint8x16_t T = vdupq_n_u8((uint8_t)(target & mask_b(4)));
    uint64_t count = 0;
    for (size_t blk = 0; blk < blocks; blk++) {
        const uint32_t *base = planar + blk * (size_t)4 * FL_LANES;
        __builtin_prefetch(base + (size_t)4 * FL_LANES, 0, 0);
        uint8x16_t acc0 = vdupq_n_u8(0), acc1 = vdupq_n_u8(0);
        for (int q = 0; q < 8; q++) {
            uint32x4_t w0 = vld1q_u32(base + 0*FL_LANES + q*4);
            uint32x4_t w1 = vld1q_u32(base + 1*FL_LANES + q*4);
            uint32x4_t w2 = vld1q_u32(base + 2*FL_LANES + q*4);
            uint32x4_t w3 = vld1q_u32(base + 3*FL_LANES + q*4);
            uint32x4_t v[32];
            v[0] = w0;
            v[1] = vshrq_n_u32(w0, 4);
            v[2] = vshrq_n_u32(w0, 8);
            v[3] = vshrq_n_u32(w0, 12);
            v[4] = vshrq_n_u32(w0, 16);
            v[5] = vshrq_n_u32(w0, 20);
            v[6] = vshrq_n_u32(w0, 24);
            v[7] = vshrq_n_u32(w0, 28);
            v[8] = w1;
            v[9] = vshrq_n_u32(w1, 4);
            v[10] = vshrq_n_u32(w1, 8);
            v[11] = vshrq_n_u32(w1, 12);
            v[12] = vshrq_n_u32(w1, 16);
            v[13] = vshrq_n_u32(w1, 20);
            v[14] = vshrq_n_u32(w1, 24);
            v[15] = vshrq_n_u32(w1, 28);
            v[16] = w2;
            v[17] = vshrq_n_u32(w2, 4);
            v[18] = vshrq_n_u32(w2, 8);
            v[19] = vshrq_n_u32(w2, 12);
            v[20] = vshrq_n_u32(w2, 16);
            v[21] = vshrq_n_u32(w2, 20);
            v[22] = vshrq_n_u32(w2, 24);
            v[23] = vshrq_n_u32(w2, 28);
            v[24] = w3;
            v[25] = vshrq_n_u32(w3, 4);
            v[26] = vshrq_n_u32(w3, 8);
            v[27] = vshrq_n_u32(w3, 12);
            v[28] = vshrq_n_u32(w3, 16);
            v[29] = vshrq_n_u32(w3, 20);
            v[30] = vshrq_n_u32(w3, 24);
            v[31] = vshrq_n_u32(w3, 28);
            uint8x16_t pk0 = vandq_u8(pack4(v[0], v[1], v[2], v[3]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk0, T));
            uint8x16_t pk1 = vandq_u8(pack4(v[4], v[5], v[6], v[7]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk1, T));
            uint8x16_t pk2 = vandq_u8(pack4(v[8], v[9], v[10], v[11]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk2, T));
            uint8x16_t pk3 = vandq_u8(pack4(v[12], v[13], v[14], v[15]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk3, T));
            uint8x16_t pk4 = vandq_u8(pack4(v[16], v[17], v[18], v[19]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk4, T));
            uint8x16_t pk5 = vandq_u8(pack4(v[20], v[21], v[22], v[23]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk5, T));
            uint8x16_t pk6 = vandq_u8(pack4(v[24], v[25], v[26], v[27]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk6, T));
            uint8x16_t pk7 = vandq_u8(pack4(v[28], v[29], v[30], v[31]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk7, T));
        }
        count += (uint64_t)vaddlvq_u8(acc0) + (uint64_t)vaddlvq_u8(acc1);
    }
    return count;
}

static uint64_t scan_b5(const uint32_t *planar, size_t blocks, uint32_t target) {
    const uint8x16_t Mb = vdupq_n_u8((uint8_t)mask_b(5));
    const uint8x16_t T = vdupq_n_u8((uint8_t)(target & mask_b(5)));
    uint64_t count = 0;
    for (size_t blk = 0; blk < blocks; blk++) {
        const uint32_t *base = planar + blk * (size_t)5 * FL_LANES;
        __builtin_prefetch(base + (size_t)5 * FL_LANES, 0, 0);
        uint8x16_t acc0 = vdupq_n_u8(0), acc1 = vdupq_n_u8(0);
        for (int q = 0; q < 8; q++) {
            uint32x4_t w0 = vld1q_u32(base + 0*FL_LANES + q*4);
            uint32x4_t w1 = vld1q_u32(base + 1*FL_LANES + q*4);
            uint32x4_t w2 = vld1q_u32(base + 2*FL_LANES + q*4);
            uint32x4_t w3 = vld1q_u32(base + 3*FL_LANES + q*4);
            uint32x4_t w4 = vld1q_u32(base + 4*FL_LANES + q*4);
            uint32x4_t v[32];
            v[0] = w0;
            v[1] = vshrq_n_u32(w0, 5);
            v[2] = vshrq_n_u32(w0, 10);
            v[3] = vshrq_n_u32(w0, 15);
            v[4] = vshrq_n_u32(w0, 20);
            v[5] = vshrq_n_u32(w0, 25);
            v[6] = vorrq_u32(vshrq_n_u32(w0, 30), vshlq_n_u32(w1, 2));
            v[7] = vshrq_n_u32(w1, 3);
            v[8] = vshrq_n_u32(w1, 8);
            v[9] = vshrq_n_u32(w1, 13);
            v[10] = vshrq_n_u32(w1, 18);
            v[11] = vshrq_n_u32(w1, 23);
            v[12] = vorrq_u32(vshrq_n_u32(w1, 28), vshlq_n_u32(w2, 4));
            v[13] = vshrq_n_u32(w2, 1);
            v[14] = vshrq_n_u32(w2, 6);
            v[15] = vshrq_n_u32(w2, 11);
            v[16] = vshrq_n_u32(w2, 16);
            v[17] = vshrq_n_u32(w2, 21);
            v[18] = vshrq_n_u32(w2, 26);
            v[19] = vorrq_u32(vshrq_n_u32(w2, 31), vshlq_n_u32(w3, 1));
            v[20] = vshrq_n_u32(w3, 4);
            v[21] = vshrq_n_u32(w3, 9);
            v[22] = vshrq_n_u32(w3, 14);
            v[23] = vshrq_n_u32(w3, 19);
            v[24] = vshrq_n_u32(w3, 24);
            v[25] = vorrq_u32(vshrq_n_u32(w3, 29), vshlq_n_u32(w4, 3));
            v[26] = vshrq_n_u32(w4, 2);
            v[27] = vshrq_n_u32(w4, 7);
            v[28] = vshrq_n_u32(w4, 12);
            v[29] = vshrq_n_u32(w4, 17);
            v[30] = vshrq_n_u32(w4, 22);
            v[31] = vshrq_n_u32(w4, 27);
            uint8x16_t pk0 = vandq_u8(pack4(v[0], v[1], v[2], v[3]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk0, T));
            uint8x16_t pk1 = vandq_u8(pack4(v[4], v[5], v[6], v[7]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk1, T));
            uint8x16_t pk2 = vandq_u8(pack4(v[8], v[9], v[10], v[11]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk2, T));
            uint8x16_t pk3 = vandq_u8(pack4(v[12], v[13], v[14], v[15]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk3, T));
            uint8x16_t pk4 = vandq_u8(pack4(v[16], v[17], v[18], v[19]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk4, T));
            uint8x16_t pk5 = vandq_u8(pack4(v[20], v[21], v[22], v[23]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk5, T));
            uint8x16_t pk6 = vandq_u8(pack4(v[24], v[25], v[26], v[27]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk6, T));
            uint8x16_t pk7 = vandq_u8(pack4(v[28], v[29], v[30], v[31]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk7, T));
        }
        count += (uint64_t)vaddlvq_u8(acc0) + (uint64_t)vaddlvq_u8(acc1);
    }
    return count;
}

static uint64_t scan_b6(const uint32_t *planar, size_t blocks, uint32_t target) {
    const uint8x16_t Mb = vdupq_n_u8((uint8_t)mask_b(6));
    const uint8x16_t T = vdupq_n_u8((uint8_t)(target & mask_b(6)));
    uint64_t count = 0;
    for (size_t blk = 0; blk < blocks; blk++) {
        const uint32_t *base = planar + blk * (size_t)6 * FL_LANES;
        __builtin_prefetch(base + (size_t)6 * FL_LANES, 0, 0);
        uint8x16_t acc0 = vdupq_n_u8(0), acc1 = vdupq_n_u8(0);
        for (int q = 0; q < 8; q++) {
            uint32x4_t w0 = vld1q_u32(base + 0*FL_LANES + q*4);
            uint32x4_t w1 = vld1q_u32(base + 1*FL_LANES + q*4);
            uint32x4_t w2 = vld1q_u32(base + 2*FL_LANES + q*4);
            uint32x4_t w3 = vld1q_u32(base + 3*FL_LANES + q*4);
            uint32x4_t w4 = vld1q_u32(base + 4*FL_LANES + q*4);
            uint32x4_t w5 = vld1q_u32(base + 5*FL_LANES + q*4);
            uint32x4_t v[32];
            v[0] = w0;
            v[1] = vshrq_n_u32(w0, 6);
            v[2] = vshrq_n_u32(w0, 12);
            v[3] = vshrq_n_u32(w0, 18);
            v[4] = vshrq_n_u32(w0, 24);
            v[5] = vorrq_u32(vshrq_n_u32(w0, 30), vshlq_n_u32(w1, 2));
            v[6] = vshrq_n_u32(w1, 4);
            v[7] = vshrq_n_u32(w1, 10);
            v[8] = vshrq_n_u32(w1, 16);
            v[9] = vshrq_n_u32(w1, 22);
            v[10] = vorrq_u32(vshrq_n_u32(w1, 28), vshlq_n_u32(w2, 4));
            v[11] = vshrq_n_u32(w2, 2);
            v[12] = vshrq_n_u32(w2, 8);
            v[13] = vshrq_n_u32(w2, 14);
            v[14] = vshrq_n_u32(w2, 20);
            v[15] = vshrq_n_u32(w2, 26);
            v[16] = w3;
            v[17] = vshrq_n_u32(w3, 6);
            v[18] = vshrq_n_u32(w3, 12);
            v[19] = vshrq_n_u32(w3, 18);
            v[20] = vshrq_n_u32(w3, 24);
            v[21] = vorrq_u32(vshrq_n_u32(w3, 30), vshlq_n_u32(w4, 2));
            v[22] = vshrq_n_u32(w4, 4);
            v[23] = vshrq_n_u32(w4, 10);
            v[24] = vshrq_n_u32(w4, 16);
            v[25] = vshrq_n_u32(w4, 22);
            v[26] = vorrq_u32(vshrq_n_u32(w4, 28), vshlq_n_u32(w5, 4));
            v[27] = vshrq_n_u32(w5, 2);
            v[28] = vshrq_n_u32(w5, 8);
            v[29] = vshrq_n_u32(w5, 14);
            v[30] = vshrq_n_u32(w5, 20);
            v[31] = vshrq_n_u32(w5, 26);
            uint8x16_t pk0 = vandq_u8(pack4(v[0], v[1], v[2], v[3]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk0, T));
            uint8x16_t pk1 = vandq_u8(pack4(v[4], v[5], v[6], v[7]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk1, T));
            uint8x16_t pk2 = vandq_u8(pack4(v[8], v[9], v[10], v[11]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk2, T));
            uint8x16_t pk3 = vandq_u8(pack4(v[12], v[13], v[14], v[15]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk3, T));
            uint8x16_t pk4 = vandq_u8(pack4(v[16], v[17], v[18], v[19]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk4, T));
            uint8x16_t pk5 = vandq_u8(pack4(v[20], v[21], v[22], v[23]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk5, T));
            uint8x16_t pk6 = vandq_u8(pack4(v[24], v[25], v[26], v[27]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk6, T));
            uint8x16_t pk7 = vandq_u8(pack4(v[28], v[29], v[30], v[31]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk7, T));
        }
        count += (uint64_t)vaddlvq_u8(acc0) + (uint64_t)vaddlvq_u8(acc1);
    }
    return count;
}

static uint64_t scan_b7(const uint32_t *planar, size_t blocks, uint32_t target) {
    const uint8x16_t Mb = vdupq_n_u8((uint8_t)mask_b(7));
    const uint8x16_t T = vdupq_n_u8((uint8_t)(target & mask_b(7)));
    uint64_t count = 0;
    for (size_t blk = 0; blk < blocks; blk++) {
        const uint32_t *base = planar + blk * (size_t)7 * FL_LANES;
        __builtin_prefetch(base + (size_t)7 * FL_LANES, 0, 0);
        uint8x16_t acc0 = vdupq_n_u8(0), acc1 = vdupq_n_u8(0);
        for (int q = 0; q < 8; q++) {
            uint32x4_t w0 = vld1q_u32(base + 0*FL_LANES + q*4);
            uint32x4_t w1 = vld1q_u32(base + 1*FL_LANES + q*4);
            uint32x4_t w2 = vld1q_u32(base + 2*FL_LANES + q*4);
            uint32x4_t w3 = vld1q_u32(base + 3*FL_LANES + q*4);
            uint32x4_t w4 = vld1q_u32(base + 4*FL_LANES + q*4);
            uint32x4_t w5 = vld1q_u32(base + 5*FL_LANES + q*4);
            uint32x4_t w6 = vld1q_u32(base + 6*FL_LANES + q*4);
            uint32x4_t v[32];
            v[0] = w0;
            v[1] = vshrq_n_u32(w0, 7);
            v[2] = vshrq_n_u32(w0, 14);
            v[3] = vshrq_n_u32(w0, 21);
            v[4] = vorrq_u32(vshrq_n_u32(w0, 28), vshlq_n_u32(w1, 4));
            v[5] = vshrq_n_u32(w1, 3);
            v[6] = vshrq_n_u32(w1, 10);
            v[7] = vshrq_n_u32(w1, 17);
            v[8] = vshrq_n_u32(w1, 24);
            v[9] = vorrq_u32(vshrq_n_u32(w1, 31), vshlq_n_u32(w2, 1));
            v[10] = vshrq_n_u32(w2, 6);
            v[11] = vshrq_n_u32(w2, 13);
            v[12] = vshrq_n_u32(w2, 20);
            v[13] = vorrq_u32(vshrq_n_u32(w2, 27), vshlq_n_u32(w3, 5));
            v[14] = vshrq_n_u32(w3, 2);
            v[15] = vshrq_n_u32(w3, 9);
            v[16] = vshrq_n_u32(w3, 16);
            v[17] = vshrq_n_u32(w3, 23);
            v[18] = vorrq_u32(vshrq_n_u32(w3, 30), vshlq_n_u32(w4, 2));
            v[19] = vshrq_n_u32(w4, 5);
            v[20] = vshrq_n_u32(w4, 12);
            v[21] = vshrq_n_u32(w4, 19);
            v[22] = vorrq_u32(vshrq_n_u32(w4, 26), vshlq_n_u32(w5, 6));
            v[23] = vshrq_n_u32(w5, 1);
            v[24] = vshrq_n_u32(w5, 8);
            v[25] = vshrq_n_u32(w5, 15);
            v[26] = vshrq_n_u32(w5, 22);
            v[27] = vorrq_u32(vshrq_n_u32(w5, 29), vshlq_n_u32(w6, 3));
            v[28] = vshrq_n_u32(w6, 4);
            v[29] = vshrq_n_u32(w6, 11);
            v[30] = vshrq_n_u32(w6, 18);
            v[31] = vshrq_n_u32(w6, 25);
            uint8x16_t pk0 = vandq_u8(pack4(v[0], v[1], v[2], v[3]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk0, T));
            uint8x16_t pk1 = vandq_u8(pack4(v[4], v[5], v[6], v[7]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk1, T));
            uint8x16_t pk2 = vandq_u8(pack4(v[8], v[9], v[10], v[11]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk2, T));
            uint8x16_t pk3 = vandq_u8(pack4(v[12], v[13], v[14], v[15]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk3, T));
            uint8x16_t pk4 = vandq_u8(pack4(v[16], v[17], v[18], v[19]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk4, T));
            uint8x16_t pk5 = vandq_u8(pack4(v[20], v[21], v[22], v[23]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk5, T));
            uint8x16_t pk6 = vandq_u8(pack4(v[24], v[25], v[26], v[27]), Mb);
            acc0 = vsubq_u8(acc0, vceqq_u8(pk6, T));
            uint8x16_t pk7 = vandq_u8(pack4(v[28], v[29], v[30], v[31]), Mb);
            acc1 = vsubq_u8(acc1, vceqq_u8(pk7, T));
        }
        count += (uint64_t)vaddlvq_u8(acc0) + (uint64_t)vaddlvq_u8(acc1);
    }
    return count;
}

uint64_t fl_scan_candidate(const uint32_t *planar, size_t n, unsigned b, uint32_t target) {
    size_t blocks = n / FL_BLOCK;
    if (b == 0) return 0;
    switch (b) {
        case 1:  return scan_b1(planar, blocks, target);
        case 2:  return scan_b2(planar, blocks, target);
        case 3:  return scan_b3(planar, blocks, target);
        case 4:  return scan_b4(planar, blocks, target);
        case 5:  return scan_b5(planar, blocks, target);
        case 6:  return scan_b6(planar, blocks, target);
        case 7:  return scan_b7(planar, blocks, target);
        default: return scan_general(planar, blocks, b, target);
    }
}
