#!/usr/bin/env python3
"""Code generator for cand_neon_sb_bulk.c — BULK PER-WORD UNPACK + BYTE-PACKED COMPARE.

For width b (1..7), each lane's 32 values occupy b consecutive 32-bit word-rows
(base[w*32 + l]). We load each of those b word-rows ONCE (8 uint32x4 vectors across
the 32 lanes), decode every output position into the low byte of a u32 lane with a
compile-time immediate shift+mask, then NARROW-PACK 4 decoded u32x4 vectors (16
values) into one u8x16 and do a SINGLE vceqq_u8 for all 16 values. This collapses
both loads (b word-rows/block) and compares (16 values per compare instead of 4),
driving ops/value down to ~0.5 and breaking past the per-position compute wall.

Per-b specialization via switch(b) keeps every shift count a compile-time immediate.
"""

LANES = 32
NVEC = 8  # 32 lanes / 4 per uint32x4

def schedule(b):
    out = []
    for p in range(32):
        bit = p * b; wp = bit >> 5; off = bit & 31
        if off == 0:
            out.append((p, wp, 'aligned', off))
        elif off + b <= 32:
            out.append((p, wp, 'inword', off))
        else:
            out.append((p, wp, 'cross', off))
    return out

def emit_fn(b):
    L = []
    nwords = b
    sched = schedule(b)
    L.append(f"static uint64_t scan_b{b}(const uint32_t *planar, size_t blocks, uint32_t target) {{")
    L.append(f"    const uint8x16_t Mb = vdupq_n_u8((uint8_t)mask_b({b}));")
    L.append(f"    const uint8x16_t T = vdupq_n_u8((uint8_t)(target & mask_b({b})));")
    L.append("    uint64_t count = 0;")
    L.append("    for (size_t blk = 0; blk < blocks; blk++) {")
    L.append(f"        const uint32_t *base = planar + blk * (size_t){b} * FL_LANES;")
    L.append(f"        __builtin_prefetch(base + (size_t){b} * FL_LANES, 0, 0);")
    # u8 accumulators: each u8 lane sums at most 8*4=32 matches per block -> fits u8,
    # widen to scalar once at block end. Two chains for ILP.
    L.append("        uint8x16_t acc0 = vdupq_n_u8(0), acc1 = vdupq_n_u8(0);")
    L.append("        for (int q = 0; q < 8; q++) {")
    for w in range(nwords):
        L.append(f"            uint32x4_t w{w} = vld1q_u32(base + {w}*FL_LANES + q*4);")
    L.append("            uint32x4_t v[32];")
    for (p, wp, kind, off) in sched:
        if kind == 'aligned':
            # value already in low byte; no shift, no mask (masked post-pack)
            L.append(f"            v[{p}] = w{wp};")
        elif kind == 'inword':
            L.append(f"            v[{p}] = vshrq_n_u32(w{wp}, {off});")
        else:
            hi = wp + 1
            L.append(f"            v[{p}] = vorrq_u32(vshrq_n_u32(w{wp}, {off}), vshlq_n_u32(w{hi}, {32-off}));")
    # pack groups of 4 -> u8x16, mask once (16 vals), compare, accumulate
    for g in range(8):
        a = f"v[{g*4}]"; bb = f"v[{g*4+1}]"; c = f"v[{g*4+2}]"; d = f"v[{g*4+3}]"
        L.append(f"            uint8x16_t pk{g} = vandq_u8(pack4({a}, {bb}, {c}, {d}), Mb);")
        accname = "acc0" if g % 2 == 0 else "acc1"
        L.append(f"            {accname} = vsubq_u8({accname}, vceqq_u8(pk{g}, T));")
    L.append("        }")
    L.append("        count += (uint64_t)vaddlvq_u8(acc0) + (uint64_t)vaddlvq_u8(acc1);")
    L.append("    }")
    L.append("    return count;")
    L.append("}")
    return "\n".join(L)

HEADER = """/* cand_neon_sb_bulk.c — Apple M4 NEON FastLanes scan, SUB-BYTE BULK PER-WORD UNPACK
 * with BYTE-PACKED COMPARE.
 *
 * Contract:
 *   uint64_t fl_scan_candidate(const uint32_t *planar, size_t n, unsigned b, uint32_t target)
 *
 * Strategy (the amortization wins, stacked):
 *  (1) BULK PER-WORD UNPACK: for width b each lane's 32 values occupy exactly b
 *      consecutive 32-bit word-rows (base[w*32 + l]). Load each word-row ONCE (8
 *      uint32x4 across the 32 lanes); every output position is decoded from those
 *      already-loaded words with a compile-time immediate shift + mask. Only the few
 *      boundary-straddling positions touch the next word (also already loaded).
 *  (2) BYTE-PACKED COMPARE: sub-byte values are <=127, so after field isolation each
 *      sits in the low byte of a u32 lane. Narrow-pack 4 decoded u32x4 (16 values)
 *      into one u8x16 and do a SINGLE vceqq_u8 for all 16 — 16 values per compare
 *      instead of 4. Matches accumulate in u16 (max 32/block/lane fits u16).
 *
 * Net: loads ~b word-rows/block; compares ~2b/block; ops/value ~0.5. Per-b switch
 * keeps all shift counts compile-time immediates. A general scalar fallback keeps a
 * full sweep (any width) correct if run without BBS_WIDTHS.
 * Generated by gen_sb_bulk.py.
 */
#include <stdint.h>
#include <stddef.h>
#include <arm_neon.h>

#define FL_LANES 32
#define FL_BLOCK 1024

static inline uint32_t mask_b(unsigned b) { return b >= 32 ? 0xFFFFFFFFu : ((1u << b) - 1u); }

/* pack 4 u32x4 (decoded value in low byte of each lane) -> one u8x16 (16 values)
 * via a narrow chain (vcombine is a free register alias; 6 vmovn do the work). */
static inline uint8x16_t pack4(uint32x4_t a, uint32x4_t b, uint32x4_t c, uint32x4_t d) {
    uint16x8_t ab = vcombine_u16(vmovn_u32(a), vmovn_u32(b));
    uint16x8_t cd = vcombine_u16(vmovn_u32(c), vmovn_u32(d));
    return vcombine_u8(vmovn_u16(ab), vmovn_u16(cd));
}

/* General scalar fallback: identical semantics to the seed, any width. */
static uint64_t scan_general(const uint32_t *planar, size_t blocks, unsigned b, uint32_t target) {
    uint32_t m = mask_b(b);
    target &= m;
    uint64_t count = 0;
    for (size_t blk = 0; blk < blocks; blk++) {
        const uint32_t *base = planar + blk * (size_t)b * FL_LANES;
        uint32_t partial[FL_LANES] = {0};
        for (unsigned p = 0; p < 32; p++) {
            unsigned bit = p * b, wp = bit >> 5, off = bit & 31;
            const uint32_t *pw = base + wp * FL_LANES;
            if (off == 0) {
                for (unsigned l = 0; l < FL_LANES; l++)
                    partial[l] += ((pw[l] & m) == target);
            } else {
                const uint32_t *pw1 = base + (wp + 1) * FL_LANES;
                for (unsigned l = 0; l < FL_LANES; l++) {
                    uint32_t v = ((pw[l] >> off) | (pw1[l] << (32 - off))) & m;
                    partial[l] += (v == target);
                }
            }
        }
        for (unsigned l = 0; l < FL_LANES; l++) count += partial[l];
    }
    return count;
}
"""

def main():
    parts = [HEADER]
    bs = list(range(1, 8))
    for b in bs:
        parts.append("\n" + emit_fn(b))
    disp = ["\nuint64_t fl_scan_candidate(const uint32_t *planar, size_t n, unsigned b, uint32_t target) {",
            "    size_t blocks = n / FL_BLOCK;",
            "    if (b == 0) return 0;",
            "    switch (b) {"]
    for b in bs:
        disp.append(f"        case {b}:  return scan_b{b}(planar, blocks, target);")
    disp.append("        default: return scan_general(planar, blocks, b, target);")
    disp.append("    }")
    disp.append("}")
    parts.append("\n".join(disp))
    with open("cand_neon_sb_bulk.c", "w") as f:
        f.write("\n".join(parts) + "\n")
    print("wrote cand_neon_sb_bulk.c")

if __name__ == "__main__":
    main()
